# Your API KEY goes here
KEY: AIzaSyA5bQ7D-b_mjjkIPHj-K4vTiWqmqsV8skc

# DB user
DB_USER: postgres

# DB name
DB_NAME: postgres   

# DB password
DB_PASSWORD: postgres

# uvicorn yutservice.main:app --reload