# Your API KEY goes here
KEY: AIzaSyA5bQ7D-b_mjjkIPHj-K4vTiWqmqsV8skc

# ----------------------Database---------------------------
POSTGRES_DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
# uvicorn yutservice.main:app --reload
